Add macOS as build target
CppUTest experiences an error in the build when building against the
default macOS 10.9 SDK.

```
error: 'operator delete' is unavailable: introduced in macOS 10.12
```

Due to this, we pin the SDK to 10.12 for v4.0 and manually set the
CXXFLAGS as mentioned in the conda-build documentation.